global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001'] # Або твоя IP адреса, якщо не працює на Windows